name: BL2016
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.375
  lightness: 0.23418499319814146
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
